import type { PluginSettings, SyncPlanEntry } from "./types";
import type { GitHubClient } from "./github-client";

export type CommitOutcome =
  | { mode: "direct"; sha: string }
  | { mode: "pr"; sha: string; number: number; url: string; branch: string };

export function commitSummary(plan: readonly SyncPlanEntry[]): string {
  return plan.map((p) => `${p.action} ${p.iconName}`).join(", ");
}

/** `figma-sync/<utc timestamp>-<first icon>[-and-N-more]`; the timestamp keeps repeated pushes of one icon apart. */
export function prBranchName(plan: readonly SyncPlanEntry[], now: Date): string {
  const stamp = now.toISOString().replace(/[-:]/g, "").replace("T", "-").slice(0, 15);
  const extra = plan.length > 1 ? `-and-${plan.length - 1}-more` : "";
  return `figma-sync/${stamp}-${plan[0]?.iconName ?? "icons"}${extra}`;
}

export function buildPrBody(plan: readonly SyncPlanEntry[]): string {
  const sections = plan.map((p) => {
    const heading = p.renamedFrom ? `${p.action} \`${p.iconName}\` (was \`${p.renamedFrom}\`)` : `${p.action} \`${p.iconName}\``;
    const changes = (p.metaChanges ?? []).map((c) => `  - ${c}`);
    const deleted = p.files.filter((f) => f.delete).length;
    const written = p.files.length - deleted;
    return [`- **${heading}** in \`${p.brand}/${p.area}\`: ${written} file(s) written, ${deleted} deleted`, ...changes].join("\n");
  });
  return ["Pushed from the Figma plugin.", "", ...sections, "", "The registry is regenerated by CI on this branch."].join("\n");
}

/** The single write step: a direct commit, or a branch plus pull request, chosen by `settings.writeMode`. */
export async function commitChanges(
  plan: readonly SyncPlanEntry[],
  settings: PluginSettings,
  client: GitHubClient
): Promise<CommitOutcome> {
  const files = plan.flatMap((p) => p.files);
  const message = `feat(icons): sync from Figma — ${commitSummary(plan)}`;

  if (settings.writeMode !== "pr") {
    return { mode: "direct", sha: await client.commitFiles(settings.branch, message, files) };
  }

  const branch = prBranchName(plan, new Date());
  await client.createBranch(branch, settings.branch);
  const sha = await client.commitFiles(branch, message, files);
  const pr = await client.openPullRequest({
    head: branch,
    base: settings.branch,
    title: message,
    body: buildPrBody(plan),
  });
  return { mode: "pr", sha, number: pr.number, url: pr.url, branch };
}
